language: node_js
node_js:
  - 13

services:
  - docker

# Pre testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no pre-scripts"

# Scripts here
script:
  - docker --version # print the version for looping
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t udagram-api-reverseproxy ./udagram-api-reverseproxy
  - docker tag udagram-api-feed joshuuua/udagram-api-feed:v1
  - docker tag udagram-api-user joshuuua/udagram-api-user:v1
  - docker tag udagram-api-frontend joshuuua/udagram-api-frontend:v1
  - docker tag udagram-api-reverseproxy joshuuua/udagram-api-reverseproxy:v1

# After scripts
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push joshuuua/udagram-api-feed:v1
  - docker push joshuuua/udagram-api-user:v1
  - docker push joshuuua/udagram-api-frontend:v1
  - docker push joshuuua/udagram-api-reverseproxy:v1